### ISSUE TITLE
Low priority font change request for visually impaired

### ISSUE THREAD

**Issue by zampaz** [pkmnct/robinhood-mint-sync-chrome#14]
The light font on the white background of RMSC is difficult to read.  Please consider darkening the font a bit if it won't ruin the style. It's a pretty style btw.  I started coding in the 79's and I thought I'd seen it all until I tried to read the instructions on the welcome screen! har har har.  Thanks for your work.  Sharing is caring and makes the world a better place :)
-Sean

**Comment by pkmnct** [comment]
I've finalized this and submitted it to the Chrome Web Store for review. There was an issue with the original submission due to a repository configuration error, so it will likely (hopefully) be denied. There does not seem to be a way to cancel that version manually since it is pending review. I will attempt to publish the corrected package as soon as I am able to.
